# What is Vectorization


Ref - https://stackoverflow.com/questions/1422149/what-is-vectorization    

**"Vectorization" (simplified) is the process of rewriting a loop so that instead of processing a single element of an array N times, it processes (say) 4 elements of the array simultaneously N/4 times.**  
    
**NUMPY Specific** - 

Vectorization is used greatly in scientific computing where huge chunks of data needs to be processed efficiently.

In real programming application ,it's used in NUMPY(not sure of other else).

Numpy (package for scientific computing in python) , uses vectorization for speedy manipulation of n-dimensional array ,which generally is slower if done with in-built python options for handling arrays.

HERE'S WHAT VECTORIZATION IS DEFINED AS IN NUMPY DOCUMENTATION PAGE

**Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code. Vectorized code has many advantages, among which are:**

1. vectorized code is more concise and easier to read
2. fewer lines of code generally means fewer bugs
3. the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)
4. vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops. </p>




Ref - https://hal.inria.fr/inria-00564007/document

In any scripting language, unjudicious use of for- loops may lead to poor performance, particularly in the case where a simple computation is applied to each element of a large data-set.
Grouping these element-wise operations together, a process known as vectorisation, allows NumPy to perform such computations much more rapidly. Suppose we have a vector a and wish to multiply its magnitude by 3. A traditional for-loop approach would look as follows


In [6]:

# Traditional for-loop approach 
import numpy as np
a = [1,3,5]
b = [3*x for x in a]
print(b)

# Vectorized approach

a = np.array([1, 3, 5])
b = 3 * a
print(b)





[3, 9, 15]
[ 3  9 15]


**Vectorized operations in NumPy are implemented in C, resulting in a significant speed improvement.** Operations are not restricted to interactions be- tween scalars and arrays. For example, here NumPy performs a fast element-wise subtraction of two arrays:

In [8]:
b-a

array([ 2,  6, 10])

When the shapes of the two arguments are not the same, but share a **common shape dimension,** the operation is broadcast across the array. In other words, NumPy expands the arrays such that the operation becomes viable:

In [16]:
m = np.arange(6).reshape(2,3)
print("M ->", m)
print("B -> ",b)
print("B+M ->",b + m)

M -> [[0 1 2]
 [3 4 5]]
B ->  [ 3  9 15]
B+M -> [[ 3 10 17]
 [ 6 13 20]]


# What is broadcasting



The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, **the smaller array is “broadcast” across the larger array so that they have compatible shapes.** Broadcasting provides a means of vectorizing array operations so that **looping occurs in C instead of Python.** It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.




In [18]:
# NumPy operations are usually done on pairs of arrays on an element-by-element basis.
# In the simplest case, the two arrays must have exactly the same shape, as in the following example:

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

# NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints.
# The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

a = np.array([1.0, 2.0, 3.0])
b = 2.0
print(a * b)


array([2., 4., 6.])

**Broadcasting Rules**

Before broadcasting two arrays, NumPy verifies that all dimensions are suitably matched. 
Dimensions match when 
  1. they are equal, or 
  2. when either is 1 or None. 
  
In the latter case, the dimension of the output array is expanded to the larger of the two.

For example, consider arrays x and y with shapes (2, 4, 3) and (4, 1) respectively. These arrays are to be combined in a broadcasting operation such as z = x + y. We match their dimensions as follows:

     ============
     x (2, 4, 3) 
     y   ( 4, 1)
     ============
     z (2, 4, 3)
     ============
     
     
Therefore, the dimensions of these arrays are compatible,and yield and output of shape(2, 4, 3).

==============================

- A      (2d array):  5 x 4
- B      (1d array):      1
- Result (2d array):  5 x 4

==============================


- A      (2d array):  5 x 4
- B      (1d array):      4
- Result (2d array):  5 x 4


==============================


- A      (3d array):  15 x 3 x 5
- B      (3d array):  15 x 1 x 5
- Result (3d array):  15 x 3 x 5


==============================


- A      (3d array):  15 x 3 x 5
- B      (2d array):       3 x 5
- Result (3d array):  15 x 3 x 5


==============================


- A      (3d array):  15 x 3 x 5
-      B      (2d array):       3 x 1
- Result (3d array):  15 x 3 x 5

==============================

